---
# Dock Configuration

## Remove any of the following items from the Dock by default
dockitems_to_remove:
  - Launchpad
  - Mail
  - Safari
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Photos
  - Messages
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - System Preferences
  - Calendar
  - Google Chrome
  - Microsoft Outlook
  - Atom
  - Quip
  - Slack
  - zoom.us
  - Self Service
  - Pages
  - Keynote
  - Numbers
  - News
  - TV
  - Podcasts
  - Music

## Setup an ordered list of dock items to set with an ordered position (left to right, 1-indexed)
#dockitems_to_persist:
#  - name: Google Chrome
#    path: "/Applications/Google Chrome.app"
#    pos: 1
#  - name: Slack
#    path: /Applications/Slack.app
#    pos: 2
#  - name: Spotify
#    path: /Applications/Spotify.app
#    pos: 3
