---
- name: Ensure GOPATH bin directory exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go/bin"
    state: directory
    mode: '0755'
  become: false

- name: Install Go tools.
  ansible.builtin.command: "go install {{ item }}"
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/go/bin"
  loop: "{{ go_tools | default([]) }}"
  become: false
  changed_when: false
